version: '3'

services:
  bot:
    build:
      context: .  # Путь к Dockerfile (текущая директория)
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bot_osor_buyer
      - DB_USER=postgres
      - DB_PASSWORD=123
    # Добавьте другие настройки, такие как порты, сети, монтирование томов, если необходимо

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bot_osor_buyer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    # Добавьте другие настройки, такие как порты, сети, монтирование томов, если необходимо
